### ISSUE TITLE
`getReqMatching`: Add support for Object params

### ISSUE THREAD

**Issue by jsspiegel** [knee-cola/jest-mock-axios#102]
I am making requests that have Array params, and am trying to search for requests with those params using `getReqMatching`. However, I am not able to do so, since `getReqMatching` ultimately uses `===` to compare the criteria params and the request params, and `===` will always return `false` in this case when comparing Objects. Ideally, I would like `getReqMatching` to be able to search for requests with Object params successfully.

Example:

```
// request: GET /api/request { params: { foo: [1, 2, 3] } }
mockAxios.getReqMatching({ url: "/api/request", method: "get", params: { foo: [1, 2, 3] } })
```

**Comment by kingjan1999** [comment]
Hi,

thank you for raising this issue. This should be fixed in 4.8.0.
