### ISSUE TITLE
Does not have axios.request just the helper methods..

### ISSUE THREAD

**Issue by gregorskii** [knee-cola/jest-mock-axios#18]
I don't think this has axios.request() can you confirm?

I tried to proxy axios.request -> axios() which is similar, that did not work, and I tried writing a switch to call the axios methods similar to how axios does it, did not work either.

This lib is much closer to working for me than others, as it can be used to mock axios in other libs that import it.

**Comment by jsgriffin** [comment]
I've also just run into this issue

**Comment by gregorskii** [comment]
@jsgriffin, in the meantime I found https://github.com/ctimmerm/axios-mock-adapter works great, but has a bit more complex serup.

**Comment by jonjaques** [comment]
See #29

**Comment by kingjan1999** [comment]
Fixed with #29
