### ISSUE TITLE
Missing cancelToken implementation

### ISSUE THREAD

**Issue by VanTanev** [knee-cola/jest-mock-axios#30]
I have a downstream library that wraps axios and uses `axios.canceToken()`: https://github.com/dai-shi/react-hooks-async/blob/master/src/use-async-task-axios.js

This breaks with `jest-mock-axios`

**Comment by kingjan1999** [comment]
Do you need a fully fledged cancel implementation or is it enough if jest-mock-axios provides a dummy implementation of `axios.CancelToken.source()` and `new axios.CancelToken()` (so that no error is thrown but cancelling itself won't work)?

**Comment by VanTanev** [comment]
For my purposes, just a mock implementation should be good. It seems like doing a full one might be too complicated.

**Comment by VanTanev** [comment]
@kingjan1999 if you're constrained for time, I can try and provide a pull request for this?

**Comment by kingjan1999** [comment]
I would do this on the weekend, but if you can do this earlier, feel free to make a pull request!

**Comment by kingjan1999** [comment]
Fixed with #32
