### ISSUE TITLE
Typescript interface for mockAxios.mockError() needlessly optional

### ISSUE THREAD

**Issue by VanTanev** [knee-cola/jest-mock-axios#31]
https://github.com/knee-cola/jest-mock-axios/blob/b4713c11001ab885c1452840d04288ab233bc8bc/lib/mock-axios-types.ts#L61

It seems that there is no reason `mockAxios.mockError()` should be optional? With the current definition, the following workaround is needed to not get type errors:
```tsx
mockAxios.mockError && mockAxios.mockError({response: { data: ['some-error']}})
```

**Comment by kingjan1999** [comment]
You're right IMO, this applies for all methods in `AxiosMockAPI`

**Comment by VanTanev** [comment]
I would believe so, yes.
