### ISSUE TITLE
finally() called to early

### ISSUE THREAD

**Issue by blalasaadri** [knee-cola/jest-mock-axios#38]
Due to https://github.com/fluffynuts/synchronous-promise/issues/15 any `.finally()` blocks on production axios calls will be called before the call is completed by using `axios.mockRequest()` or `axios.mockError()` if synchronous-promise 2.0.9 is used. Increasing the dependency like such:
```json
"dependencies": {
  "synchronous-promise": "^2.0.10"
}
```
should fix this issue though.

**Comment by kingjan1999** [comment]
Thank you for reporting! I will look into this on Sunday, but feel free to submit a PR before.

**Comment by kingjan1999** [comment]
I updated the dependency with e7855bf79555a5ce4bc6a1e32da37e35e33b59fd. The commit is included in version 3.1.1, which was just published to npm.
