### ISSUE TITLE
Mocking axios.CancelToken

### ISSUE THREAD

**Issue by ezra-m** [knee-cola/jest-mock-axios#45]
I understand that jest-mock-axios provides axios cancel interfaces, but does anyone have any examples of how they have implemented this, specifically mocking axios.CancelToken?

Thanks.

**Comment by kingjan1999** [comment]
Hi,

as described in the README, the current mock of `CancelToken` is there to prevent any errors (see #30 and #32).

So basically, this (taken from the axios README) works:
```typescript
const makeAndCancelRequest = () => {
  const CancelToken = axios.CancelToken;
  const source = CancelToken.source();

  axios
    .get("/user/12345", {
      cancelToken: source.token
    })
    .catch(function(thrown) {
      if (axios.isCancel(thrown)) {
      } else {
        // handle error
      }
    });

  source.cancel("Operation canceled by the user.");
};
```

```typescript
it("does not throw error if used", () => {
  expect(() => makeAndCancelRequest()).not.toThrowError();
});
```

Do you need some more implementation here?

**Comment by ezra-m** [comment]
Perfect, thank you.

**Comment by Hamidrezana** [comment]
I didn't understand how to use this implementation.
```
import axios from "axios";
const CancelToken = axios.CancelToken;
let cancel;

export const getCarsFromServer = car => {
  cancel && cancel();
  return new Promise((resolve, reject) => {
    axios
      .get("http://localhost:5000", {
        params: {
          car
        },
        cancelToken: new CancelToken(function executor(c) {
          cancel = c;
        })
      })
      .then(res => resolve(res.data))
      .catch(err => {
        if (axios.isCancel(err)) {
          console.log("post Request canceled");
        } else {
          reject();
        }
      });
  });
};
```
This is my code that I want to test.
What should I do with your implementation.

**Comment by kingjan1999** [comment]
@Hamidrezana Do you want to test if calling `getCarsFromServer` another time while the first request is still running cancels the first one? In that case: This currently doesn't work with `jest-mock-axios` - sorry!

**Comment by Hamidrezana** [comment]
@kingjan1999 Yes, Anyway tnx.

**Comment by dducrest** [comment]
Hi @kingjan1999, I'm looking to something similar. 

I worked around the functionality by mocking CancelToken.source.cancel(errorString?:string) function to create an object that passes Axios.isCancel(error) test. 

`
cancelToken.source.cancel = jest.fn((errorString?: string) => {
            mockAxios.mockError({ toString: () => { return errorString; }, __CANCEL__: 1 });
        });
`

The error passed to your request's catch will pass `axios.isCancel(error) == true`

**Comment by Harut101** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/36543683/80198106-ab607900-8630-11ea-9127-f544f65fa8f6.png)
how can I make mock?

**Comment by kingjan1999** [comment]
Please note: Actually cancelling requests is now supported with version 4.0

**Comment by suresh777** [comment]
I am facing same issue, any update
  TypeError: Cannot read property 'source' of undefined

  const CancelToken = axios.CancelToken;
    const source = CancelToken.source();

**Comment by kingjan1999** [comment]
> I am facing same issue while running testcases, any update
> TypeError: Cannot read property 'source' of undefined
> 
> const CancelToken = axios.CancelToken;
> const source = CancelToken.source();

@suresh777  Are you using the latest version of this lib? Can you post a minimal example?
