### ISSUE TITLE
axiosClientInstance.interceptors.request.use not supported?

### ISSUE THREAD

**Issue by timotgl** [knee-cola/jest-mock-axios#5]
The code I'm trying to test looks like this:

```
const axiosClientInstance = axios.create(someConfigObject);
axiosClientInstance.interceptors.request.use((config) => {
    config.headers.common['Access-Token'] = accessToken;
    return config;
});
```

Jest gives the following error:
```
TypeError: Cannot read property 'request' of undefined
```

Had to resort to some trickery to stub the call to the interceptors, but I'm not sure this worked:

```
// __mocks__/axios.js

import mockAxios from 'jest-mock-axios';

export default {
    ...mockAxios,
    ...{
        create: jest.fn(() => ({
            ...mockAxios,
            interceptors: {
                request: {
                    use: jest.fn()
                }
            }
        })),
    }
};
```

After doing this, `axiosClientInstance.put()` does not return a promise anymore. Is there any way currently to stub the interceptors properly?

**Comment by knee-cola** [comment]
I'm sorry to say, but interceptors are currently not supported. I hope to find some time and implement this feature (can't promise when). You're welcome to implement it yourself and make a pull request :)

**Comment by chrisjlee** [comment]
Trying to do this too. Might be a dumb question could you possible provide some insight what would it take to get this working?

**Comment by VictorCazanave** [comment]
I was looking for the same feature and I think there is a typo in the [README](https://github.com/knee-cola/jest-mock-axios#missing-features) that misled me : "AxiosMock coveres the most popular parts of Axios API, meaning that some of the features are **~~not~~** missing (i.e. interceptors)."
(English is not my native language, so I may be wrong 👼 )

**Comment by Graham42** [comment]
In case someone ends up here from google

```__mocks__/axios.ts
/* __mocks__/axios.ts */
import { AxiosStatic } from "axios";

const mockAxios = jest.genMockFromModule<AxiosStatic>("axios");

console.log("in mock setup");
mockAxios.interceptors = mockAxios.interceptors || {};
mockAxios.interceptors.response = mockAxios.interceptors.response || {};
mockAxios.interceptors.response.use = jest.fn();
mockAxios.create = () => {
  console.log("in mock create");
  return mockAxios;
};

export default mockAxios;
```

```__tests__/thing.spec.ts
/* __tests__/thing.spec.ts */
// seems to be important to have this before the module import
const mockAxios: jest.Mocked<AxiosStatic> = require("axios").default;

import { thingUsingAxios } from "../thing";

  it("basic", async () => {
    mockAxios.post.mockImplementationOnce(async (...args) => ({
      status: 200,
      data: {},
      headers: {},
      config: {},
      statusText: "ok",
    }));

  // call thing
  // verify something
})

```

**Comment by kingjan1999** [comment]
Hi,

thank your for reporting this issue. I've implemented basic support for interceptors (as already presented here and in #23) with version 2.3.0 (just published on npm). Please try and report back.
