### ISSUE TITLE
Request to add changelog

### ISSUE THREAD

**Issue by doutatsu** [knee-cola/jest-mock-axios#51]
I've recently noticed that this package have been updated to 4.0.0. But It's hard to see all the changes since 3.2.0, I am currently on. I'd like to suggest adding a changelog, which would make it easier to update this package. This should also let dependabot handle this library better

**Comment by kingjan1999** [comment]
Hi, 

there is a changelog already in the [releases tab](https://github.com/knee-cola/jest-mock-axios/releases). I am not familiar with dependabot, so I don't know how it would profit from a separate changelog file.

**Comment by doutatsu** [comment]
Thanks for a prompt answer @kingjan1999, I should have checked releases tab. [dependabot](https://dependabot.com/) lets you manage dependencies automatically and is extremely useful because of that. It was even acquired by Github.

If you have a changelog, when your package is updated, it will show that changelog in the PRs it makes for projects that use your dependency, like this:

![](https://user-images.githubusercontent.com/4270980/82753732-da007980-9dbf-11ea-9bd0-672ac43e2646.png)

**Comment by kingjan1999** [comment]
Added in  ba74cb5
