### ISSUE TITLE
axios.mockErrorFor 

### ISSUE THREAD

**Issue by Emidomenge** [knee-cola/jest-mock-axios#55]
Hello,

First of all, great job for this lib, I like it a lot. :)

Just a request if it's possible to do a function `axios.mockErrorFor` which will behave same as `axios.mockResponseFor` but sending an error ?

Or is there a workaround to do it ?

Thanks !

**Comment by kingjan1999** [comment]
Hi,

you should be able to use `getReqMatching` to get the request info and then use it as a second parameter for `mockError` (see docs) to replicate the behavior of `mockResponseFor`.

Adding `mockErrorFor` might be interesting for symmetry reasons, but it would only be a mere abstraction over existing methods as described above.

Hope this helps for now...

**Comment by Emidomenge** [comment]
Ok, it works indeed, I put an example which can be useful I think:

Some context: 
_I have many requests triggered in background (they can arrive in a random order) and I need to mock only a specific one._ 

```javascript

        // getting the extended info about the most recent request
        const lastReqInfo = MockAxios.lastReqGet();
        // getting the promise made when the most recent request was made
        const lastPromise = MockAxios.lastPromiseGet();
        if (lastReqInfo && lastReqInfo.url.includes('/myApiThatIWantToTarget')) {
            mockAxios.mockError(loopScheduler[loopIndex], lastReqInfo);
        }
```
