### ISSUE TITLE
Question: Does jest.mock('axios') get called automatically? 

### ISSUE THREAD

**Issue by cmacdonnacha** [knee-cola/jest-mock-axios#61]
Not an issue, just a question. 

Before using this wonderful library I would always have to use `jest.mock('axios')` at the top of my test to ensure that real api calls were not being made. I was wondering if this is now called by default inside your library?

**Comment by kingjan1999** [comment]
Hi,

calling `jest.mock` shouldn't be necessary when using ES6 module imports with Jest (from the [docs](https://jestjs.io/docs/en/manual-mocks#using-with-es-module-imports): "If you're using ES module imports then you'll normally be inclined to put your import statements at the top of the test file. But often you need to instruct Jest to use a mock before modules use it. *For this reason, Jest will automatically hoist jest.mock calls to the top of the module (before any imports).*")

**Comment by cmacdonnacha** [comment]
Great thanks!
