### ISSUE TITLE
MockAxios.defaults is different on github from published npm package

### ISSUE THREAD

**Issue by CezarManea** [knee-cola/jest-mock-axios#92]
In version 4.7.0-beta3 the `MockAxios.defaults` is different from github code.
https://www.npmjs.com/package/jest-mock-axios/v/4.7.0-beta3?activeTab=explore
```
MockAxios.defaults = {
  headers: {
    common: []
  }
};
```
vs
https://github.com/knee-cola/jest-mock-axios/blob/v4.7.0-beta3/lib/mock-axios.ts#L137
```
MockAxios.defaults = {
    headers: {
        common: [],
        get: {},
        post: {},
        delete: {},
        put: {},
        patch: {},
        head: {}
    },
};
```
Maybe something is broken in the publishing pipeline? @kingjan1999

**Comment by kingjan1999** [comment]
Should be fixed with `4.7.0-beta4`, sorry for the inconvenience
