### ISSUE TITLE
types are no longer exported

### ISSUE THREAD

**Issue by RichardHpa** [knee-cola/jest-mock-axios#97]
I am currently upgrading the package from 4.5.0 to 4.7.1.
In the latest version you are no longer exporting your types for some of your interfaces so it causes any project that uses the types now breaks a typeCheck

here is a screenshot from my editor of the file at node_modules/jest-mock-axios/dist/index.d.ts

![Screenshot 2023-05-01 at 2 25 34 PM](https://user-images.githubusercontent.com/26518752/235392943-2908cb7b-519d-4d7b-92ec-54df0d73e898.png)

**Comment by kingjan1999** [comment]
Hi,

thank you for raising this issue and sorry for the delayed reaction. This should be fixed in `4.7.2` which I just published on npm.
